version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      github_actions_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      pip_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      pip_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
