{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-funnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funnel
  template:
    metadata:
      labels:
        app: funnel
    spec:
      containers:
        - name: funnel
          image: {{ .Values.image | quote }}
          args: ["funnel", "server", "run", "--config", "/etc/funnel/funnel.conf"]
          ports:
            - containerPort: 8000
            - containerPort: 9090
          volumeMounts:
            - name: conf
              mountPath: /etc/funnel/funnel.conf
              subPath: funnel.conf
      volumes:
        - name: conf
          configMap:
            name: {{ .Release.Name }}-funnel-conf
{{- end }}
