services:
  sapporo:
    image: ghcr.io/sapporo-wes/sapporo-service:latest
    ports:
      - "1122:1122"
    volumes:
      - sapporo_runs:/opt/sapporo/runs
      - ./config/sapporo/executable_workflows.json:/app/executable_workflows.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=1122
    restart: unless-stopped

volumes:
  sapporo_runs:
